In [34]:
#Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import scipy.stats as sts
import gmaps
import gmaps.geojson_geometries
import time
from pprint import pprint

#Import API Keys
from config import (gkey, ckey)

In [31]:
covid_data=pd.read_csv("Resources/us-counties.csv")
covid_data=covid_data.loc[covid_data["date"]== "2020-07-29"]
covid_data.reset_index(drop=True, inplace=True)

In [32]:
covid_data["Lat"]=""
covid_data["Lng"]=""
covid_data

            date      county    state     fips  cases  deaths Lat Lng
0     2020-07-29     Autauga  Alabama   1001.0    987      21
1     2020-07-29     Baldwin  Alabama   1003.0   2908      21
2     2020-07-29     Barbour  Alabama   1005.0    584       4
3     2020-07-29        Bibb  Alabama   1007.0    344       2
4     2020-07-29      Blount  Alabama   1009.0    694       3
...          ...         ...      ...      ...    ...     ...  ..  ..
3212  2020-07-29  Sweetwater  Wyoming  56037.0    234       2
3213  2020-07-29       Teton  Wyoming  56039.0    318       1
3214  2020-07-29       Uinta  Wyoming  56041.0    245       1
3215  2020-07-29    Washakie  Wyoming  56043.0     44       5
3216  2020-07-29      Weston  Wyoming  56045.0      5       0

[3217 rows x 8 columns]

In [35]:
#This cell takes a little over an hour to run
params={"key":gkey}
for index,row in covid_data.iterrows():
    base_url="https://maps.googleapis.com/maps/api/geocode/json"
    county=row["county"]
    state=row["state"]
    params["address"]=f"{county},{state}"
    result=requests.get(base_url, params=params)
    result=result.json()
    try:    
        covid_data.loc[index, "Lat"] = result["results"][0]["geometry"]["location"]["lat"]
        covid_data.loc[index, "Lng"] = result["results"][0]["geometry"]["location"]["lng"]
        time.sleep(1)
    except (IndexError, KeyError):
        print("results not found...skipping")
        time.sleep(1)
print("-"*30)
print("Complete")

results not found...skipping
------------------------------
Complete

In [55]:
covid_data[["Lat","Lng"]]=covid_data[["Lat","Lng"]].apply(pd.to_numeric,axis=1)
covid_data.dropna(subset=["Lat"],inplace=True)

In [56]:
covid_data

,date,county,state,fips,cases,deaths,Lat,Lng
0,2020-07-29,Autauga,Alabama,1001.0,987,21,32.579182,-86.499655
1,2020-07-29,Baldwin,Alabama,1003.0,2908,21,30.601074,-87.776333
2,2020-07-29,Barbour,Alabama,1005.0,584,4,31.817290,-85.354965
3,2020-07-29,Bibb,Alabama,1007.0,344,2,32.956280,-87.142289
4,2020-07-29,Blount,Alabama,1009.0,694,3,34.014515,-86.499655
...,...,...,...,...,...,...,...,...
3212,2020-07-29,Sweetwater,Wyoming,56037.0,234,2,41.851940,-109.188005
3213,2020-07-29,Teton,Wyoming,56039.0,318,1,43.853632,-110.631449
3214,2020-07-29,Uinta,Wyoming,56041.0,245,1,41.210740,-110.616892
3215,2020-07-29,Washakie,Wyoming,56043.0,44,5,43.006346,-108.882346
3216,2020-07-29,Weston,Wyoming,56045.0,5,0,44.636927,-105.336105

In [57]:
gmaps.configure(api_key=gkey)
locations=covid_data[["Lat","Lng"]]
case_count=covid_data["cases"]

In [58]:
fig=gmaps.figure()
heat_layer=gmaps.heatmap_layer(locations,weights=case_count,dissipating=False,point_radius=2,
                              max_intensity=case_count.max())
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))