In [3]:
#Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import scipy.stats as sts
import gmaps
from pprint import pprint

#Import API Keys
from config import (gkey, ckey)

In [20]:
covid_data=pd.read_csv("Resources/us-counties.csv")
covid_data=covid_data.loc[covid_data["date"]== "2020-07-29"]

In [19]:
covid_data["Lat"]=""
covid_data["Lng"]=""
covid_data

              date      county    state     fips  cases  deaths Lat Lng
379550  2020-07-29     Autauga  Alabama   1001.0    987      21
379551  2020-07-29     Baldwin  Alabama   1003.0   2908      21
379552  2020-07-29     Barbour  Alabama   1005.0    584       4
379553  2020-07-29        Bibb  Alabama   1007.0    344       2
379554  2020-07-29      Blount  Alabama   1009.0    694       3
...            ...         ...      ...      ...    ...     ...  ..  ..
382762  2020-07-29  Sweetwater  Wyoming  56037.0    234       2
382763  2020-07-29       Teton  Wyoming  56039.0    318       1
382764  2020-07-29       Uinta  Wyoming  56041.0    245       1
382765  2020-07-29    Washakie  Wyoming  56043.0     44       5
382766  2020-07-29      Weston  Wyoming  56045.0      5       0

[3217 rows x 8 columns]

In [22]:
params={"key":gkey}
for index,row in covid_data.iterrows():
    base_url="https://maps.googleapis.com/maps/api/geocode/json"
    county=row["county"]
    state=row["state"]
    params["address"]=f"{county},{state}"
    result=requests.get(base_url, params=params)
    result=result.json()
    try:    
        covid_data.loc[index, "Lat"] = result["results"][0]["geometry"]["location"]["lat"]
        covid_data.loc[index, "Lng"] = result["results"][0]["geometry"]["location"]["lng"]
    except (IndexError, KeyError):
        print("results not found...skipping")
print("-"*30)
print("Complete")

IndexError: list index out of range

In [24]:
covid_data

,date,county,state,fips,cases,deaths,Lat,Lng
379550,2020-07-29,Autauga,Alabama,1001.0,987,21,32.579182,-86.499655
379551,2020-07-29,Baldwin,Alabama,1003.0,2908,21,30.601074,-87.776333
379552,2020-07-29,Barbour,Alabama,1005.0,584,4,31.817290,-85.354965
379553,2020-07-29,Bibb,Alabama,1007.0,344,2,32.956280,-87.142289
379554,2020-07-29,Blount,Alabama,1009.0,694,3,34.014515,-86.499655
...,...,...,...,...,...,...,...,...
382762,2020-07-29,Sweetwater,Wyoming,56037.0,234,2,NaN,NaN
382763,2020-07-29,Teton,Wyoming,56039.0,318,1,NaN,NaN
382764,2020-07-29,Uinta,Wyoming,56041.0,245,1,NaN,NaN
382765,2020-07-29,Washakie,Wyoming,56043.0,44,5,NaN,NaN
382766,2020-07-29,Weston,Wyoming,56045.0,5,0,NaN,NaN

In [15]:
gmaps.configure(api_key=gkey)
locations=covid_data["county"]
case_count=covid_data["cases"]

In [18]:
fig=gmaps.figure()
heat_layer=gmaps.heatmap_layer(locations,weights=case_count,dissipating=False,point_radius=2,
                              max_intensity=case_count.max())
fig.add_layer(heat_layer)
fig

TypeError: heatmap_layer() got an unexpected keyword argument 'data'